insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Batedeira','Melhor batedeira do mundo.',150.5,10.4,50,'foto-batedeira.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Geladeira','Melhor Geladeira do mundo.',1250.5,10.4,50,'foto-Geladeira.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Fogao','Melhor Fogao do mundo.',750.5,10.4,50,'foto-Fogao.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Liquidificador','Melhor Liquidificador do mundo.',150.5,10.4,50,'foto-Liquidificador.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Sofa','Melhor Sofa do mundo.',150.5,10.4,50,'foto-batedeira.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Laca-louça','Melhor Laca-louça do mundo.',1250.5,10.4,50,'foto-Laca-louça.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Maquina de Lavar','Melhor Maquina de Lavar do mundo.',750.5,10.4,50,'foto-Maquina de Lavar.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Secador de cabelo','Melhor Secador de cabelo do mundo.',150.5,10.4,50,'foto-Secador de cabelo.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Guarda-roupa','Melhor Guarda-roupa do mundo.',150.5,10.4,50,'foto-Guarda-roupa.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Micro Ondas','Melhor batedeira do mundo.',150.5,10.4,50,'foto-Micro Ondas.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Ferro eletrico','Melhor Geladeira do mundo.',1250.5,10.4,50,'foto-Ferro eletrico.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Conjunto de panelas','Melhor Conjunto de panelas do mundo.',750.5,10.4,50,'foto-Conjunto de panelas.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Caixa de ferramentas','Melhor Caixa de ferramentas do mundo.',150.5,10.4,50,'foto-Caixa de ferramentas.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Cama de casal','Melhor Cama de casal do mundo.',150.5,10.4,50,'foto-Cama de casal.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Fruteira','Melhor Fruteira do mundo.',1250.5,10.4,50,'foto-Fruteira.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Video game','Melhor Video game do mundo.',750.5,10.4,50,'foto-Video game.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Almofada','Melhor Almofada do mundo.',150.5,10.4,50,'foto-Almofada.jpg');
insert into `produto` (`nome`, `descricao`, `preco`, `desconto`, `estoque`, foto) values ('Lustre','Melhor Lustre do mundo.',150.5,10.4,50,'foto-Lustre.jpg');

insert into `cliente` (`nome`, `cpf`, `email`, `senha`, `perfil`) values ('Admin','11111111111','admin@admin.com','d033e22ae348aeb5660fc2140aec35850c4da997', 'CLIENTE');
